package com.ecerejo;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem02 {

	public static void main(String[] args) {
		Problem02 problem02 = new Problem02();
		System.out.println(problem02.resolve(4000000));

	}

	private long resolve(int limit) {
		
		/* starting first two numbers in Fibonacci sequence and its even sum */ 
		long previous  = 1;
		long current = 2;
		long sumFibonacci = 2;
		long next;
		
		while (current <= limit) {
			next = previous + current;
			previous = current;
			current = next;
			
			if(current%2 == 0) {
				sumFibonacci += current;
			}
		}
		return sumFibonacci;
	}

}
